### ISSUE TITLE
Filtering lines added and deleted

### ISSUE THREAD

**Issue by pcampion1** [AlexIljin/regexPreFilter#2]
I can get this plugin to work for lines changed but not for lines added or deleted. Is this feature supported?

**Comment by alex-ilin** [comment]
I'm not entirely sure what you are talking about. This plugin allows one to ignore changes inside lines. For example, you can configure it to ignore a date-time prefix in a log file, thus comparing only the log contents. If a line was added or deleted, it can't be ignored altogether.

**Comment by pcampion1** [comment]
I have added this to the Winmerge forum as I dont really understand why line filters cant also be used for additions and deletions as well. In the meantime I have had to implement a different non-elegant regex solution using grep.

**Comment by alex-ilin** [comment]
A change filter only helps WinMerge decide whether a line should be considered modified or not modified. If a line is added, how can it be _not modified?_ Or if a line was deleted, how can it be the same as a _not deleted_ line?

I guess you want a file-level filter, not a line-level one. You could run your file through [sed](https://en.wikipedia.org/wiki/Sed) prior to comparison, so that only the lines you are interested in are left in the file. Maybe you could use a different contents filter for that, or write a new one. I think you could make an "unpacker" plugin, which would pretend to decompress a file, while actually it would filter the lines and produce a filtered output. That's a different type of plugin, though, from the WinMerge prespective.
